//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apnetTareasMVC_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREAS
    {
        public int ID { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> TIPO { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<int> PRIORIDAD { get; set; }
        public List<TIPO> ColeccionDeTipos { get; internal set; }
        public List<PRIORIDAD> coleccionDePrioridad { get; internal set; }
    }
}
