//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apnetTareasMVC_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class USUARIOS
    {
        public int ID { get; set; }

        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public Nullable<int> EDAD { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public string DEBAJA { get; set; }
        [DisplayName("usuario")]
        [Required(ErrorMessage = "este campo es requerido")]
        public string USERID { get; set; }

        [DataType(DataType.Password)]
        [DisplayName("Contraseña")]
        [Required(ErrorMessage = "este campo es requerido")]
        public string PASSWORD { get; set; }

        public string loginErrorMessage{ get; set; }


}
}
